# Generated by Django 5.2.7 on 2025-10-25 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('discription', models.TextField()),
                ('image', models.ImageField(upload_to='service/images')),
            ],
        ),
    ]
